# Generated by Django 3.0.2 on 2020-10-25 17:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticket', '0005_auto_20201025_2310'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Support_model',
            new_name='Support',
        ),
    ]
