# Generated by Django 3.0.2 on 2020-10-25 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0007_auto_20201025_2315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='support',
            old_name='user',
            new_name='user_profile',
        ),
    ]
