# Generated by Django 3.0.2 on 2020-10-25 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0008_auto_20201025_2338'),
    ]

    operations = [
        migrations.CreateModel(
            name='ticket_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_profile', models.CharField(max_length=200)),
                ('ticket_id', models.IntegerField(null=True)),
            ],
        ),
    ]
