# Generated by Django 3.0.2 on 2020-10-25 18:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticket', '0009_ticket_data'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Support',
            new_name='Profile',
        ),
        migrations.DeleteModel(
            name='ticket_data',
        ),
    ]
